spring.application.name=gemini-demo

server.port=5000

# Gemini AI Configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-pro-preview

# Ensure your logs are visible
logging.level.root=INFO

# Log File Configuration
logging.file.name=logs/application.log

# If you want to see detailed SQL or Hibernate errors for your task-tracker
# logging.level.org.hibernate.SQL=DEBUG